name: Deploy Monitoring


on:
  push:
    branches: [dev]

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # kubeconfig
      - name: Setup kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
          echo "KUBECONFIG=$PWD/kubeconfig" >> $GITHUB_ENV

      # OPTIONAL DEBUG
      - name: Verify cluster connection
        run: |
          kubectl get nodes

      - name: Apply k8s manifests (no image change)
        run: |
          kubectl apply -f k8s/monitoring -n dev
          kubectl get deployments -n dev -o name \
            | xargs -n1 kubectl rollout restart -n dev
          kubectl rollout status deployment -n dev --timeout=180s
