name: Deploy Monitoring

on:
  push:
    branches:
      - dev

jobs:
  deploy-monitoring:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Set kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Verify cluster connection
        run: kubectl get nodes

      - name: Deploy Monitoring
        run: kubectl apply -f k8s/monitoring/

      - name: Verify deployment
        run: kubectl get pods -n monitoring-dev -o wide
